<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-QCK44TB" name="com.testng.Basic" tests="5" failures="0" timestamp="2022-12-16T14:51:19 IST" time="2.296" errors="1">
  <testcase name="dog" time="0.049" classname="com.testng.Basic"/>
  <testcase name="cat" time="2.085" classname="com.testng.Basic">
    <error type="org.testng.TestException" message="
Expected exception of type class org.testng.internal.thread.ThreadTimeoutException but got java.lang.InterruptedException: sleep interrupted">
      <![CDATA[org.testng.TestException: 
Expected exception of type class org.testng.internal.thread.ThreadTimeoutException but got java.lang.InterruptedException: sleep interrupted
at org.testng.internal.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:68)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:719)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:616)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.InterruptedException: sleep interrupted
at java.lang.Thread.sleep(Native Method)
at com.testng.Basic.cat(Basic.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:51)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:41)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNoExecutor(MethodInvocationHelper.java:313)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:279)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:590)
... 9 more
]]>
    </error>
  </testcase> <!-- cat -->
  <testcase name="pen" time="0.048" classname="com.testng.Basic"/>
  <testcase name="apple" time="0.066" classname="com.testng.Basic"/>
  <testcase name="book" time="0.048" classname="com.testng.Basic"/>
</testsuite> <!-- com.testng.Basic -->
